"""add is_active to vendors

Revision ID: 2754aa39d52c
Revises: 7059f66478eb
Create Date: 2026-07-06 17:08:15.294716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2754aa39d52c'
down_revision: Union[str, Sequence[str], None] = '7059f66478eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "vendors",
    sa.Column(
        "is_active",
        sa.Boolean(),
        nullable=False,
        server_default=sa.true(),
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'is_active')
    # ### end Alembic commands ###
